version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dawcasino_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dawcasino2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./dawCasino2Back
    container_name: dawcasino_backend
    restart: always
    ports:
      - "8989:8989"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dawcasino2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./dawCasino2Front
    container_name: dawcasino_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: